chaoss/grimoirelab-kingarthur

tests/__init__.py
tests/test_worker.py

As the unit tests need a connection with a Redis database, a "real" server must be up to run the tests.  With this change, this "real" server is replaced by fakeredis library to emulate the use of a server.

[tests] Modify unit test for Arthur Worker using fakeredis module instead of redis

---

requirements.txt
setup.py
tests/test_arthur.py
tests/test_jobs.py

This PR fixes the missing distribution six>=1.11.0.
The problem is due to the fact that **cheerypy** requires the dependency with **six** to be >=1.11.0. However this distribution is not available for python 3.4.
The proposed solution sets the **cheerpy** dependency to >=8.1, <=11.0.0 (versions that do not force **six** to be greater than 1.11.0). An alternative solution could be to use of python 3.4 instead of 3.5.

[setup] Fix six>=1.11.0 distribution not found

---

bin/arthurd

This new feature will allow to launch `arthurd` using an `.ini` configuration file:
```
$ arthurd --config <path_to_config_file>
```
The configuration file will have the following format:
```
[arthur]
cache_path = <path_to_cache>
debug = <True or False>
log_path = <path_to_log>
no_cache = <True or False>
sync_mode = <True or False>
[connection]
host = <Host IP address>
port=<port number>
[elasticsearch]
es_index = <ElasticSearch URL>
[redis]
database = <Redis URL>
```

Add support for configuration file in `arthurd`

---

README.md

This new section includes how to run `arthurd` using a configuration file and an example of its structure.

Update documentation with information about arthurd configuration file

---

arthur/jobs.py
arthur/scheduler.py
tests/test_jobs.py

So far, when a job runs in the 'update' queue and no new items are fetched, either 'from_date' or 'offset' values are reset to the starting values defined for the parent task (in backend_args).
This is an error because jobs in 'update' must start from the point where the previous job ended.
Fixes #27

[jobs] Fix 'from_date' and 'offset' reset error

---

README.md
arthur/arthur.py
arthur/jobs.py
arthur/scheduler.py
tests/test_arthur.py
tests/test_jobs.py
tests/test_scheduler.py

This function only needs `max_retries` parameter but it was getting the full set of arguments.

Remove job sched args from execute_perceval_job

---

arthur/jobs.py
tests/test_server.py

This code includes the category within the backend arguments before calling Perceval. Thus, it allows to deal with backends with multiple categories.

[jobs] Add category to backend arguments

---

arthur/arthur.py
tests/test_arthur.py
tests/test_tasks.py

This code enables validation of the tasks sent to the Arthur server. It checks that `task_id`, `backend`, `category` are not null or empty as well as it makes sure that the `backend_args` is a dict (if defined).

[arthur] Add validation for tasks

---

arthur/events.py
arthur/scheduler.py
arthur/worker.py
tests/test_events.py
tests/test_worker.py

This PR decouples the event listener from the job scheduler. So far, the listener was tight to the scheduler and only used to reschedule tasks. With this PR it will be possible to listed to other kind of events and to have specific handlers for each events.
It's also possible to subscribe to events and to unsubscribe from them.
Once this solution is accepted, the next step will be to decouple handlers from the scheduler (now they are methods of the `Scheduler` class). To decouple it, it will be necessary to refactor some parts of the scheduler.
Fixes #50.

Refactor events listener to decouple it from job scheduler

---

arthur/scheduler.py
arthur/tasks.py
tests/test_scheduler.py
tests/test_tasks.py

This PR defines the different statuses a task could have during its life cycle. Statuses are described in the documentation.
The PR is not well tested because it's hard to do it with the current structure. To do that, the next step would be to refactor the `JobScheduler` into a `TaskScheduler`, so life cycle will be more easier to understand and task jobs will be only generated when they are enqueued in a **RQ** queue. Once this is done, it will be also possible to extract `_handle_successful_job` and `_handle_failed_job` into **callables**. Therefore, we will be able to test them separately. Not like at this moment, because they run within a thread.
With this refactoring it will be possible to test the change of status from one stage to another and to start working on #48.

Task status

---

arthur/scheduler.py
arthur/tasks.py
tests/test_scheduler.py
tests/test_tasks.py

Following the description of #55, this PR refactors the Job scheduler into a Task scheduler. Jobs are only internal to the Task scheduler. Queue selection has been also delegated to the scheduler and some names were renamed.

Refactor Job scheduler

---

arthur/events.py
arthur/scheduler.py
arthur/worker.py
tests/test_events.py
tests/test_scheduler.py
tests/test_worker.py

This PR adds a new type of event: `JobEvent.STARTED` that is handled by the scheduler. When this event is handled, the scheduler is able to set the task that generate the job to `RUNNING`. This adds the feature requested in #60 .
To implement this feature it was also needed to include the task identifier within the `JobEvent` object. The reason to do this is all the handlers need the task identifier, so it makes sense to include it in the event instead of looking for it.

Started job events

---

arthur/jobs.py
arthur/scheduler.py
arthur/server.py
arthur/tasks.py
tests/test_jobs.py
tests/test_scheduler.py
tests/test_server.py
tests/test_tasks.py

This PR contains some modifications to keep the history of task jobs.
First, it includes a new attribute in `Task` objects to store the list of jobs id. This list will be updated by the scheduler once the job is enqueued.
TTL of jobs and results were modified, so they won't deleted from the database. This will keep the history.
Detailed jobs history can be obtained using the REST API call `task`. Giving the task identificator, this method will return all the information related to the task and its jobs.
This PR adds the feature described in #61 .

Store task jobs

---

tests/test_server.py

The current tests were running with real repositories. This can make the testing fail and non-deterministic.
This commit replaces these repos by those stored in 'tests/data' directory.

Fix server tests with non-real repositories

---

arthur/scheduler.py
arthur/tasks.py
tests/test_scheduler.py
tests/test_server.py
tests/test_tasks.py

This PR allows to re-schedule tasks only a limited number of times (as was requested in #48).
A new parameter 'max_age' is available to define the lifetime of a tasks. When a tasks reaches it, it will be set as COMPLETED. Otherwise, it will be rescheduled.

Tasks lifetime

---

arthur/server.py
tests/test_server.py

This PR adds a new endpoint to the CherryPy server that will return the job data using the resource /job/<job_id>. It includes also the corresponding test.
Related to #79

Add new endpoint that expose jobs

---

bin/arthurd

This PR addresses https://github.com/chaoss/grimoirelab-kingarthur/issues/85. In a nutshell, the params `--no-daemon` and `--log-path` are set as mutually exclusive. If Arthurd is run as daemon, the log messages are set to `log-path` (by default `os.path.expanduser('~/.arthur/logs/')`), otherwise the log messages are sent to `stderr`.

[bin] Send arthur messages to stderr if --no-daemon is on

---

arthur/scheduler.py
arthur/server.py
arthur/tasks.py
tests/test_scheduler.py
tests/test_server.py
tests/test_tasks.py

Summarizing, the changes was to change the list of job_id strings that were included in the task object for a list of objects that each object includes the job_id field and the job_number (changes made in the scheduler).
Moreover, in the server, it has been needed a change in the task query, adding the field job_number field in the list of jobs that it returned.
Related to #104

Add job_number to the tasks and task queries

---

arthur/common.py
arthur/scheduler.py
bin/arthurw
tests/test_scheduler.py

Now, all failed tasks are sent to a new queue named `retry`.
Before this change, when a task failed inside the `create` queue it was re-scheduled into `update` queue.
This PR aims to solve issue https://github.com/chaoss/grimoirelab-kingarthur/issues/93.

[scheduler] Reschedule failed tasks into the retry queue

---

arthur/arthur.py
arthur/errors.py
arthur/scheduler.py
arthur/server.py
arthur/tasks.py
bin/arthurd
tests/test_arthur.py
tests/test_errors.py
tests/test_jobs.py
tests/test_scheduler.py
tests/test_tasks.py

This PR addresses https://github.com/chaoss/grimoirelab-kingarthur/issues/88. In a nutshell, tasks are now saved in redis. This implies some changes in the scheduler, arthur and task registry.
New tests have been provided, old ones have been updated accordingly.

store tasks using redis

---

arthur/arthur.py
arthur/scheduler.py
arthur/server.py
tests/test_arthur.py
tests/test_scheduler.py
tests/test_server.py

This series of commits allow to re-schedule tasks that failed at some point. When a failed tasks is re-schedule some of its properties are reset. Specifically, the age of the task and the number of failures are reset to 0.
The commits include also the API REST call `reschedule` that allow to run again a set of tasks.
This commit fulfills the requirements of issue #76.

Reschedule failed tasks
